---
id: Vfs
name: Vfs
full: Virtual file system library
description: >-
  A library that provides a Virtual File System API, with backends for SQL, FTP,
  Local filesystems, Hybrid SQL and filesystem, Samba, SSH2/SFTP, MongoDB.
  Reading, writing and listing of files are all supported.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Vfs
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Core: ^2
      pear.horde.org/Horde_Db: ^2.4
      pear.horde.org/Horde_Kolab_Session: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Mongo: ^1
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Test: ^2.1
      pecl.php.net/ssh2:
        version: ^0.12 || ^1
        providesextension: ssh
    ext:
      ftp: '*'
